"""Add is_archived to tasks and jobs

Revision ID: 0fb19a3bf6d4
Revises: 4025b2661ffa
Create Date: 2025-12-08 00:49:57.383355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb19a3bf6d4'
down_revision: Union[str, None] = '4025b2661ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether job is archived'))
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether task is archived'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_archived')
    op.drop_column('jobs', 'is_archived')
    # ### end Alembic commands ###
