"""Add username column to users

Revision ID: d5e5edcedeae
Revises: d1b07709bc9c
Create Date: 2025-12-06 06:48:53.026925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e5edcedeae'
down_revision: Union[str, None] = 'd1b07709bc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username'))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment="User's full name")
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment="User's full name")
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
