/**
 * Type definitions for the Annotations Sidebar
 */

import type { Annotation, Label, AnnotationType } from '@/types/annotations';

// Filter mode for annotations
export type FilterMode = 'all' | 'manual' | 'auto';

// Sort mode for table
export type SortMode = 'newest' | 'oldest' | 'confidence-high' | 'confidence-low' | 'type' | 'label';

// Appearance settings for canvas display
export interface AppearanceSettings {
  fillOpacity: number;      // 0-100
  selectedOpacity: number;  // 0-100
  strokeWidth: number;      // pixels
  showLabels: boolean;
  showPolygons: boolean;
  showRectangles: boolean;
  showHoverTooltips: boolean;
}

// Table row data structure
export interface AnnotationTableRow {
  id: string;
  index: number;                    // Display index (1-based)
  type: AnnotationType;
  labelId: string;
  labelName: string;
  labelColor: string;
  confidence?: number;              // 0-1 for auto-generated
  isAutoGenerated: boolean;
  isVisible: boolean;
  dimensions: string;               // "120x80" or "5 pts" or "(x, y)"
  area: number;                     // For sorting (rectangle area or polygon points)
  createdAt: number;
  originalAnnotation: Annotation;   // Reference to original annotation
}

// Main sidebar props
export interface AnnotationsSidebarProps {
  // Data
  annotations: Annotation[];
  labels: Label[];

  // Selection state
  selectedAnnotations: string[];
  selectedLabelId: string | null;

  // Selection handlers
  onSelectAnnotations: (ids: string[]) => void;
  onSelectLabel: (id: string) => void;

  // Deletion handlers
  onDeleteAnnotation: (id: string) => void;
  onBulkDeleteAnnotations: (ids: string[]) => void;

  // Modification handlers
  onBulkChangeLabel: (annotationIds: string[], newLabelId: string) => void;
  onLabelChange: (annotationId: string, newLabelId: string) => void;
  onToggleAnnotationVisibility: (annotationId: string) => void;
  onBulkToggleVisibility: (annotationIds: string[]) => void;

  // Sidebar state
  isCollapsed: boolean;
  onToggleCollapse: () => void;

  // Appearance settings
  appearanceSettings?: AppearanceSettings;
  onAppearanceChange?: (settings: AppearanceSettings) => void;
  appearanceDefaults?: AppearanceSettings;
}

// Filter tabs props
export interface FilterTabsProps {
  filterMode: FilterMode;
  onFilterChange: (mode: FilterMode) => void;
  counts: {
    all: number;
    manual: number;
    auto: number;
  };
}

// Label dropdown cell props
export interface LabelDropdownCellProps {
  row: AnnotationTableRow;
  labels: Label[];
  onLabelChange: (annotationId: string, newLabelId: string) => void;
}

// Bulk actions panel props
export interface BulkActionsPanelProps {
  selectedCount: number;
  labels: Label[];
  onBulkChangeLabel: (newLabelId: string) => void;
  onBulkDelete: () => void;
  onClearSelection: () => void;
  onBulkToggleVisibility: () => void;
}

// Appearance section props
export interface AppearanceSectionProps {
  settings: AppearanceSettings;
  defaults: AppearanceSettings;
  onChange: (settings: AppearanceSettings) => void;
  isExpanded: boolean;
  onToggle: () => void;
}

// Annotations table props
export interface AnnotationsTableProps {
  data: AnnotationTableRow[];
  labels: Label[];
  selectedIds: Set<string>;
  onRowClick: (id: string, event: React.MouseEvent) => void;
  onSelectionChange: (ids: string[]) => void;
  onLabelChange: (annotationId: string, newLabelId: string) => void;
  onToggleVisibility: (id: string) => void;
  onDelete: (id: string) => void;
}

// Fallback appearance defaults
export const FALLBACK_APPEARANCE_DEFAULTS: AppearanceSettings = {
  fillOpacity: 0,
  selectedOpacity: 30,
  strokeWidth: 2,
  showLabels: false,
  showPolygons: true,
  showRectangles: true,
  showHoverTooltips: true,
};

// Sidebar width constants
export const MIN_SIDEBAR_WIDTH = 320;
export const MAX_SIDEBAR_WIDTH = 600;
export const DEFAULT_SIDEBAR_WIDTH = 380;
export const COLLAPSED_SIDEBAR_WIDTH = 48;

// LocalStorage keys
export const SIDEBAR_WIDTH_KEY = 'annotationsSidebarWidth';
export const SIDEBAR_SECTIONS_KEY = 'annotationsSidebarSections';
