/**
 * Type definitions for the Annotations Sidebar
 */

import type { Annotation, Label, AnnotationType } from '@/types/annotations';

// Filter mode for annotations
export type FilterMode = 'all' | 'manual' | 'auto';

// Sort mode for table
export type SortMode = 'newest' | 'oldest' | 'confidence-high' | 'confidence-low' | 'type' | 'label';

// Dim level for highlight mode (5 levels as requested)
export type DimLevel = 'none' | 'light' | 'subtle' | 'medium' | 'strong' | 'very-strong';

// Dim level opacity mapping
export const DIM_LEVEL_MAP: Record<DimLevel, number> = {
  'none': 0,
  'light': 0.2,
  'subtle': 0.3,
  'medium': 0.5,
  'strong': 0.7,
  'very-strong': 0.85,
};

// Appearance settings for canvas display
export interface AppearanceSettings {
  fillOpacity: number;      // 0-100
  selectedOpacity: number;  // 0-100
  strokeWidth: number;      // pixels
  showLabels: boolean;
  showPolygons: boolean;
  showRectangles: boolean;
  showHoverTooltips: boolean;
  // Highlight mode settings
  highlightMode: boolean;   // Enable/disable background dimming
  dimLevel: DimLevel;       // Dim intensity level
  // Tiny annotation detection
  tinyThreshold: number;    // 1-5% (annotations below this are marked as tiny)
}

// Table row data structure
export interface AnnotationTableRow {
  id: string;
  index: number;                    // Display index (1-based)
  type: AnnotationType;
  labelId: string;
  labelName: string;
  labelColor: string;
  confidence?: number;              // 0-1 for auto-generated
  isAutoGenerated: boolean;
  isVisible: boolean;
  dimensions: string;               // "120x80" for rectangles, "(x, y)" for points
  pointCount: number;               // Number of points (polygons) or 0 for rectangles/points
  area: number;                     // Pixel area for rectangles/polygons, 0 for points
  areaPercentage: number;           // Percentage of image area (0-100)
  isTiny: boolean;                  // True if below threshold percentage
  hasAttributes: boolean;           // True if annotation has custom attributes
  createdAt: number;
  originalAnnotation: Annotation;   // Reference to original annotation
}

// Main sidebar props
export interface AnnotationsSidebarProps {
  // Data
  annotations: Annotation[];
  labels: Label[];

  // Selection state
  selectedAnnotations: string[];
  selectedLabelId: string | null;

  // Selection handlers
  onSelectAnnotations: (ids: string[]) => void;
  onSelectLabel: (id: string) => void;

  // Deletion handlers
  onDeleteAnnotation: (id: string) => void;
  onBulkDeleteAnnotations: (ids: string[]) => void;

  // Modification handlers
  onBulkChangeLabel: (annotationIds: string[], newLabelId: string) => void;
  onLabelChange: (annotationId: string, newLabelId: string) => void;
  onToggleAnnotationVisibility: (annotationId: string) => void;
  onBulkToggleVisibility: (annotationIds: string[]) => void;
  onUpdateAnnotationAttributes?: (annotationId: string, attributes: Record<string, string | number | boolean>) => void;

  // Sidebar state
  isCollapsed: boolean;
  onToggleCollapse: () => void;

  // Image dimensions (for calculating area percentage)
  imageWidth?: number;
  imageHeight?: number;

  // Appearance settings
  appearanceSettings?: AppearanceSettings;
  onAppearanceChange?: (settings: AppearanceSettings) => void;
  appearanceDefaults?: AppearanceSettings;
}

// Filter tabs props
export interface FilterTabsProps {
  filterMode: FilterMode;
  onFilterChange: (mode: FilterMode) => void;
  counts: {
    all: number;
    manual: number;
    auto: number;
  };
}

// Label dropdown cell props
export interface LabelDropdownCellProps {
  row: AnnotationTableRow;
  labels: Label[];
  onLabelChange: (annotationId: string, newLabelId: string) => void;
}

// Bulk actions panel props
export interface BulkActionsPanelProps {
  selectedCount: number;
  labels: Label[];
  onBulkChangeLabel: (newLabelId: string) => void;
  onBulkDelete: () => void;
  onClearSelection: () => void;
  onBulkToggleVisibility: () => void;
}

// Appearance section props
export interface AppearanceSectionProps {
  settings: AppearanceSettings;
  defaults: AppearanceSettings;
  onChange: (settings: AppearanceSettings) => void;
  isExpanded: boolean;
  onToggle: () => void;
}

// Annotations table props
export interface AnnotationsTableProps {
  data: AnnotationTableRow[];
  labels: Label[];
  selectedIds: Set<string>;
  tinyThreshold: number;
  onRowClick: (id: string, event: React.MouseEvent) => void;
  onSelectionChange: (ids: string[]) => void;
  onLabelChange: (annotationId: string, newLabelId: string) => void;
  onToggleVisibility: (id: string) => void;
  onDelete: (id: string) => void;
  onEditAttributes?: (annotationId: string) => void;
}

// Fallback appearance defaults
export const FALLBACK_APPEARANCE_DEFAULTS: AppearanceSettings = {
  fillOpacity: 0,
  selectedOpacity: 30,
  strokeWidth: 2,
  showLabels: false,
  showPolygons: true,
  showRectangles: true,
  showHoverTooltips: true,
  highlightMode: false,
  dimLevel: 'medium',
  tinyThreshold: 2,
};

// Sidebar width constants
export const MIN_SIDEBAR_WIDTH = 320;
export const MAX_SIDEBAR_WIDTH = 600;
export const DEFAULT_SIDEBAR_WIDTH = 380;
export const COLLAPSED_SIDEBAR_WIDTH = 48;

// LocalStorage keys
export const SIDEBAR_WIDTH_KEY = 'annotationsSidebarWidth';
export const SIDEBAR_SECTIONS_KEY = 'annotationsSidebarSections';
