// Tool types
export type Tool = 'select' | 'rectangle' | 'polygon' | 'point'

// Annotation types
export type AnnotationType = 'rectangle' | 'polygon' | 'point'

// Prompt mode types
export type PromptMode = 'single' | 'auto-apply' | 'batch'

// Label group definition
export interface LabelGroup {
  id: string
  name: string
  isExpanded?: boolean // UI state: expanded/collapsed
  isVisible?: boolean // Group-level visibility toggle (affects all child labels)
  sortOrder?: number // Custom ordering
  createdAt: number
}

// Attribute type for label attribute definitions
export type AttributeType = 'text' | 'number' | 'boolean' | 'select';

// Label attribute definition (schema for annotation attributes)
export interface LabelAttributeDefinition {
  id: string
  name: string
  type: AttributeType
  required?: boolean
  defaultValue?: AttributeValue
  options?: string[] // For 'select' type - available options
  description?: string
  min?: number // For 'number' type - minimum value
  max?: number // For 'number' type - maximum value
}

// Label definition
export interface Label {
  id: string
  name: string
  color: string
  createdAt: number
  // Group and visibility fields (optional for backward compatibility)
  groupId?: string // Parent group ID (null/undefined = ungrouped)
  isVisible?: boolean // Individual label visibility toggle (default: true)
  sortOrder?: number // Custom ordering within group
  // Attribute schema for annotations with this label
  attributeDefinitions?: LabelAttributeDefinition[]
}

// Attribute value type (supports text, number, boolean)
export type AttributeValue = string | number | boolean;

// Base annotation interface
export interface BaseAnnotation {
  id: string
  imageId: string
  labelId: string
  type: AnnotationType
  createdAt: number
  updatedAt: number
  confidence?: number // Prediction confidence score (0-1) for auto-generated annotations
  isAutoGenerated?: boolean // Flag to distinguish auto-generated from manual annotations
  isVisible?: boolean // Individual annotation visibility toggle (default: true)
  backendId?: string // Backend annotation ID (for synced annotations in team mode)
  originalFrontendId?: string // Original frontend ID that never changes (used to prevent ID corruption during sync)
  attributes?: Record<string, AttributeValue> // Custom key-value attributes (like CVAT)
  source?: string // 'manual' | 'model:{model_id}' | 'import'
}

// Rectangle annotation
export interface RectangleAnnotation extends BaseAnnotation {
  type: 'rectangle'
  x: number
  y: number
  width: number
  height: number
}

// Polygon annotation
export interface PolygonAnnotation extends BaseAnnotation {
  type: 'polygon'
  points: Array<{ x: number; y: number }>
}

// Point annotation
export interface PointAnnotation extends BaseAnnotation {
  type: 'point'
  x: number
  y: number
}

// Union type for all annotations
export type Annotation = RectangleAnnotation | PolygonAnnotation | PointAnnotation

// Image metadata
export interface ImageData {
  id: string
  name: string
  relativePath?: string
  displayName: string
  width: number
  height: number
  blob: Blob
  createdAt: number
  // Job mode fields (optional)
  s3Key?: string  // S3/MinIO key for job images
  jobImageId?: string  // Backend image ID for sync
  jobId?: number  // Job ID for URL construction
}

// Project (collection of images and annotations)
export interface Project {
  id: string
  name: string
  createdAt: number
  updatedAt: number
}

// Edit mode state
export interface EditMode {
  annotationId: string
  type: AnnotationType
}

// COCO Export types
export interface COCOInfo {
  year: number
  version: string
  description: string
  contributor: string
  url?: string
  date_created: string
}

export interface COCOImage {
  id: number
  file_name: string
  width: number
  height: number
  date_captured?: string
}

export interface COCOCategory {
  id: number
  name: string
  supercategory: string
}

export interface COCOAnnotation {
  id: number
  image_id: number
  category_id: number
  bbox?: [number, number, number, number] // [x, y, width, height]
  segmentation?: number[][] // polygon points
  area?: number
  iscrowd: 0 | 1
  attributes?: Record<string, string | number | boolean> // Custom annotation attributes
}

export interface COCODataset {
  info: COCOInfo
  images: COCOImage[]
  annotations: COCOAnnotation[]
  categories: COCOCategory[]
}

// SAM3 API Response Types (inlined from shared-types)
export interface BoundingBox {
  x1: number
  y1: number
  x2: number
  y2: number
}

export interface MaskPolygon {
  polygons: Array<Array<[number, number]>>
  area: number
}

export interface InferenceResult {
  num_objects: number
  boxes: Array<[number, number, number, number]>
  scores: number[]
  masks: MaskPolygon[]
  processing_time_ms: number
  visualization_base64?: string
}

export interface BatchImageResult {
  image_index: number
  num_objects: number
  boxes: Array<[number, number, number, number]>
  scores: number[]
  masks: MaskPolygon[]
  visualization_base64?: string
}

export interface BatchInferenceResult {
  total_images: number
  results: BatchImageResult[]
  total_processing_time_ms: number
  average_time_per_image_ms: number
}

export interface APIResponse<T> {
  data: T
  message: string
  status_code: number
}

export type SAM3Response = APIResponse<InferenceResult>
export type SAM3BatchResponse = APIResponse<BatchInferenceResult>
export type SAM3Mask = MaskPolygon

// Loading state types
export type LoadingPhase =
  | 'initial'
  | 'loading-critical'
  | 'ready'
  | 'background-loading'
  | 'complete'

export interface LoadingProgress {
  phase: LoadingPhase
  current: number
  total: number
  percentage: number
  currentStep: string
  subProgress?: {
    message: string
    current: number
    total: number
  }
}
