import type { Annotation } from '@/types/annotations'

export interface DedupOptions {
  iouThreshold: number // 0-1, boxes at or above this IoU are duplicates
  containmentThreshold: number // 0-1, a box this fully inside another is a duplicate
  sameLabelOnly: boolean // only compare annotations sharing a label
}

export interface DuplicateGroup {
  keep: Annotation
  remove: Annotation[]
}

export interface DedupResult {
  groups: DuplicateGroup[]
  removeIds: string[]
}

export const DEFAULT_DEDUP_OPTIONS: DedupOptions = {
  iouThreshold: 0.85,
  containmentThreshold: 0.9,
  sameLabelOnly: true,
}

interface Box {
  x0: number
  y0: number
  x1: number
  y1: number
}

/** Axis-aligned bounds for any annotation type. Points have zero area and are never deduped. */
function getBox(ann: Annotation): Box | null {
  if (ann.type === 'rectangle') {
    return {
      x0: Math.min(ann.x, ann.x + ann.width),
      y0: Math.min(ann.y, ann.y + ann.height),
      x1: Math.max(ann.x, ann.x + ann.width),
      y1: Math.max(ann.y, ann.y + ann.height),
    }
  }
  if (ann.type === 'polygon') {
    if (ann.points.length < 3) return null
    const xs = ann.points.map(p => p.x)
    const ys = ann.points.map(p => p.y)
    return { x0: Math.min(...xs), y0: Math.min(...ys), x1: Math.max(...xs), y1: Math.max(...ys) }
  }
  return null
}

const area = (b: Box) => Math.max(0, b.x1 - b.x0) * Math.max(0, b.y1 - b.y0)

function intersectionArea(a: Box, b: Box): number {
  const w = Math.min(a.x1, b.x1) - Math.max(a.x0, b.x0)
  const h = Math.min(a.y1, b.y1) - Math.max(a.y0, b.y0)
  return w > 0 && h > 0 ? w * h : 0
}

export function boxIoU(a: Box, b: Box): number {
  const inter = intersectionArea(a, b)
  const union = area(a) + area(b) - inter
  return union > 0 ? inter / union : 0
}

/** Fraction of the smaller box that lies inside the larger one. */
function containment(a: Box, b: Box): number {
  const inter = intersectionArea(a, b)
  const smaller = Math.min(area(a), area(b))
  return smaller > 0 ? inter / smaller : 0
}

/**
 * Ranks which annotation of an overlapping pair to keep.
 * Manual beats auto-generated, then higher confidence, then polygon over
 * rectangle (more geometry), then larger area, then older.
 */
function keepScore(ann: Annotation): number[] {
  const box = getBox(ann)
  return [
    ann.isAutoGenerated ? 0 : 1,
    ann.confidence ?? 0,
    ann.type === 'polygon' ? 1 : 0,
    box ? area(box) : 0,
    -ann.createdAt,
  ]
}

function compareKeep(a: Annotation, b: Annotation): number {
  const sa = keepScore(a)
  const sb = keepScore(b)
  for (let i = 0; i < sa.length; i++) {
    if (sa[i] !== sb[i]) return sb[i] - sa[i]
  }
  return 0
}

/**
 * Greedy NMS-style duplicate detection, scoped per image.
 * Returns which annotations to keep and which overlapping ones to drop.
 */
export function findDuplicateAnnotations(
  annotations: Annotation[],
  options: DedupOptions = DEFAULT_DEDUP_OPTIONS
): DedupResult {
  const byImage = new Map<string, Annotation[]>()
  annotations.forEach(ann => {
    if (!getBox(ann)) return
    const list = byImage.get(ann.imageId) || []
    list.push(ann)
    byImage.set(ann.imageId, list)
  })

  const groups: DuplicateGroup[] = []

  byImage.forEach(imageAnns => {
    const sorted = [...imageAnns].sort(compareKeep)
    const consumed = new Set<string>()

    for (let i = 0; i < sorted.length; i++) {
      const keep = sorted[i]
      if (consumed.has(keep.id)) continue
      const keepBox = getBox(keep)!
      const remove: Annotation[] = []

      for (let j = i + 1; j < sorted.length; j++) {
        const other = sorted[j]
        if (consumed.has(other.id)) continue
        if (options.sameLabelOnly && other.labelId !== keep.labelId) continue

        const otherBox = getBox(other)!
        const isDuplicate =
          boxIoU(keepBox, otherBox) >= options.iouThreshold ||
          containment(keepBox, otherBox) >= options.containmentThreshold

        if (isDuplicate) {
          consumed.add(other.id)
          remove.push(other)
        }
      }

      if (remove.length > 0) {
        groups.push({ keep, remove })
      }
    }
  })

  return {
    groups,
    removeIds: groups.flatMap(g => g.remove.map(a => a.id)),
  }
}
